### ISSUE TITLE
index23.html is not mirrored

### ISSUE THREAD

**Issue by k26pl** [Explosion-Scratch/illuminati#1]
index23.html is not mirrored

**Comment by Explosion-Scratch** [comment]
I recursively followed all links, I can manually add it though

**Comment by k26pl** [comment]
i also found https://academy.illuminatiorder.info/ and https://academy.illuminatiorder.info/mss.htm

**Comment by Explosion-Scratch** [comment]
Working on cloning, please make a new issue
