### ISSUE TITLE
mirror academy.illuminatiorder.info

### ISSUE THREAD

**Issue by k26pl** [Explosion-Scratch/illuminati#3]
academy.illuminatiorder.info

**Comment by k26pl** [comment]
there are also 2 subdomains
board.illuminatiorder.info - broken phpbb
horus.illuminatiorder.info - broken wordpress

**Comment by Explosion-Scratch** [comment]
Already fixed in `c6c865a8d1deaf1ed9bee9335d93e1bf9e6582c4`

**Comment by Explosion-Scratch** [comment]
> there are also 2 subdomains board.illuminatiorder.info - broken phpbb horus.illuminatiorder.info - broken wordpress

No point cloning those, they're broken
