### ISSUE TITLE
can you create a project for notes?

### ISSUE THREAD

**Issue by k26pl** [Explosion-Scratch/illuminati#4]
i`ve found https://academy.illuminatiorder.info/stats , and may find more. can you create a project so i will be able to make public what i discover?

**Comment by k26pl** [comment]
https://academy.illuminatiorder.info/entry.html
https://academy.illuminatiorder.info/academy.php - blank page (maybe php generates some content with correct post/get args)
https://academy.illuminatiorder.info/main.html
https://academy.illuminatiorder.info/portal.htm
https://academy.illuminatiorder.info/portal.html
https://academy.illuminatiorder.info/test1.html
https://academy.illuminatiorder.info/test2.html
https://academy.illuminatiorder.info/test3.html

**Comment by kamilko2006kk** [comment]
http://www5.illuminatiorder.eu/

**Comment by Explosion-Scratch** [comment]
> https://academy.illuminatiorder.info/stats

Unauthorized, can't download
