### ISSUE TITLE
more links

### ISSUE THREAD

**Issue by k26pl** [Explosion-Scratch/illuminati#5]
https://www.illuminatiorder.info/bookof/dead164.htm
https://www.illuminatiorder.info/bookof
https://www.illuminatiorder.info/krad/fokoob/daed.htm
https://illuminatiorder.info/krad/32xedni.html
https://illuminatiorder.info/index23.html
https://www.illuminatiorder.info/bookof/dead.htm

**Comment by Explosion-Scratch** [comment]
> https://illuminatiorder.info/krad/32xedni.html

Doesn't exist

> https://illuminatiorder.info/index23.html
Already exists
