### ISSUE TITLE
more links

### ISSUE THREAD

**Issue by k26pl** [Explosion-Scratch/illuminati#7]
https://www.illuminatiorder.info/a2/o21/
https://www.illuminatiorder.info/a2/o21/astronomy.htm
https://www.illuminatiorder.info/a2/o21/alchemy.htm
https://www.illuminatiorder.info/a2/o21/pics/hyperspace/l23p.htm
https://www.illuminatiorder.info/a2/o21/pics/hyperspace/
https://www.illuminatiorder.info/a2/o21/1000angels/final.htm
https://www.illuminatiorder.info/a2/o21/libretto.htm - the house of ... is link to dead board(probanly phpbb), and linkto   password goes to yachoo group that redirect to yachoo.com

**Comment by k26pl** [comment]
web archive indexed yachoo group 3 times, all of them have a lot of redirects, 2 show an error and 3rd is a redirect loop

**Comment by k26pl** [comment]
https://web.archive.org/web/20080705173000/http://www.illuminatiorder.info/board/forumdisplay.php4?f=60

**Comment by Explosion-Scratch** [comment]
Make a PR
